# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5722feeb0770d3bc2c40cd137eb58d084938af3e6903e9c5bcdf4d37fd4eebbacb7eaf9b3dc5f799d356805b7c51de411efb2bf3d3a47b36e26909313cb75f6a

test:
  secret_key_base: 91fa41f28d6825b154f9517a3fba727d59d205797cdb07dc32f2edaa6102ea6e0112c5bef169e7559c44b4a757ee58e5e787b8551aa1697798a7bacbc90b4e6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
