# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cdcc9a79dbfb982159ac63d8d7af899afc8dd26d1fc3f1cc35e9324fd2115a3b55f9ccddffe8da44facd097b231f77a73f344893bcb0437f47bf06fd0d371cc

test:
  secret_key_base: 4ba37d69a39acd907cac3b6f79d330d5552716301ec838fd62cc871a6d45c934f38158e7d84ecd2e37da69e856d35044e488b7637089bc7d83ba51a7e804701c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
