# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22d354c9b667919a8002c2e8e682b0284b3fa0d7e5ce8d8c31c9b38e085e5fd62fbafe2472fa84301d0f30034ff4c9c5514011a3a4d4b5654f848fcf12e1c2c3

test:
  secret_key_base: 573385ef9d61f04fab8851dc673cd2db111544f1232f1158c20a8c1f82abb2f5e11634cc0e801fcff232e6f45c96a1366b5ba7a884797fd36cf632e37865a4ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
