# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 518dfe5b18581ba2374eacea01b9c7575f38f28e36fcbdfc4342408a95269ebc374f817aa5d9ed978aaf368d4455aa402597f9440f0f7244b06da1d9e313e43b

test:
  secret_key_base: 28124f6b2cfdb73b88dfb4811c554cf3b20f6dffc606ddbfb982bb0e4a72221fffbade49af58965631f2fdf16f206f16e257b786935c4d9f91a83d62e1ae5fde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
