# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51313fd8f96eb92c330365d9acb53da27f5aee874eaa7e40d5d2eca2b07f633777c25ff064d99b7af39b890b94d321c4cb12464db3e4b52e491a5745e61a3b34

test:
  secret_key_base: 3f42b71c86b99bf4417eded9d6f977ad7f8ac158da676fab86f1c51bb2aa1a6b00f7733f441eb69b26c919ddfd88e17bd813808c81b089fc8b73dd4dc67f0ee7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
