# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad95f9b7f4751be6372fe77bfc8c31f34a998a0eba674c0245dacf3f1bbed7df628090fd1f6cf18ebe8b41e1b0f400ff3d2f07984b261073653f4d8e4cdee22e

test:
  secret_key_base: 56d0dcafac5d7b01a235d54619fc5d96175c75f8712a640e4dd899e61850d9ae35909c4d589852cddfd5ef7307f74703b4851452d077214a8eb53077c5458fd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
