# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e1232b0d1c424dc6ed9a7c025515eae9110e1b850a386f902e62e5c405c72f2e437edc190276bfed6afb72ad68b1afca5279bf0b7a6d68ec3098f6db9e723fe

test:
  secret_key_base: 8174d5a83ac2e4ae9d1f98cd58732972a0fd481d7bc7d96d877f90f3fdabe66508b87d181caaa023e0f20831df9039a035cc8d1aee1a25a4cf443f16f98562f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
