# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93a83d8b3b053995f3616cf61ba0a91070223728b62bde52f815d39e6d7ff9b756c085beaddd61b315331113d3007dc9ff287a67c9473e959797656e4442a557

test:
  secret_key_base: a12abf1ad464d0f91153cc2e2cebf675da4a72d2af703a50c810e303e5301e67c0cee9313d862a2b9bd9f94a09369d796a39a21da88494ee94d9c14c75272ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
